# Generated by Django 4.0 on 2021-12-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Useremail', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
                ('userPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
